/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject28 struct {
	// The reason the user has been kicked. This will be supplied as the  ``reason`` on the target's updated `m.room.member`_ event.
	Reason string `json:"reason,omitempty"`
	// The fully qualified user ID of the user being kicked.
	UserId string `json:"user_id"`
}
