/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type LoginFlow struct {
	// The login type. This is supplied as the ``type`` when logging in.
	Type string `json:"type,omitempty"`
}
