/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Notification struct {
	// The action(s) to perform when the conditions for this rule are met. See `Push Rules: API`_.
	Actions []string `json:"actions"`
	// The Event object for the event that triggered the notification.
	Event map[string]interface{} `json:"event"`
	// The profile tag of the rule that matched this event.
	ProfileTag string `json:"profile_tag,omitempty"`
	// Indicates whether the user has sent a read receipt indicating that they have read this message.
	Read bool `json:"read"`
	// The ID of the room in which the event was posted.
	RoomId string `json:"room_id"`
	// The unix timestamp at which the event notification was sent, in milliseconds.
	Ts int32 `json:"ts"`
}
