/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2004 struct {
	// Each key is an identitfier for one of the user's devices.
	Devices map[string]DeviceInfo `json:"devices,omitempty"`
	// The Matrix user ID of the user.
	UserId string `json:"user_id,omitempty"`
}
