/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Filter to apply to the results.
type Filter struct {
	// A string to search for in the room metadata, e.g. name, topic, canonical alias etc. (Optional).
	GenericSearchTerm string `json:"generic_search_term,omitempty"`
}
