/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20048 struct {
	// The byte-size of the image. Omitted if there is no image attached.
	Matriximagesize int64 `json:"matrix:image:size,omitempty"`
	// An `MXC URI`_ to the image. Omitted if there is no image.
	Ogimage string `json:"og:image,omitempty"`
}
