/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20014 struct {
	// The ID of each room in which the user has ``joined`` membership.
	JoinedRooms []string `json:"joined_rooms"`
}
