/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20010 struct {
	// An array of events.
	Chunk []map[string]interface{} `json:"chunk,omitempty"`
	// A token which correlates to the last value in ``chunk``. This token should be used in the next request to ``/events``.
	End string `json:"end,omitempty"`
	// A token which correlates to the first value in ``chunk``. This is usually the same token supplied to ``from=``.
	Start string `json:"start,omitempty"`
}
