/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject31 struct {
	// The reason the content is being reported. May be blank.
	Reason string `json:"reason"`
	// The score to rate this content as where -100 is most offensive and 0 is inoffensive.
	Score int32 `json:"score"`
}
