/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20040 struct {
	// The ID of the filter that was created. Cannot start with a ``{`` as this character is used to determine if the filter provided is inline JSON or a previously declared filter by homeservers on some APIs.
	FilterId string `json:"filter_id"`
}
