/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20022 struct {
	// Whether the user is currently active
	CurrentlyActive bool `json:"currently_active,omitempty"`
	// The length of time in milliseconds since an action was performed by this user.
	LastActiveAgo int32 `json:"last_active_ago,omitempty"`
	// This user's presence.
	Presence string `json:"presence"`
}
