/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Tag struct {
	// A number in a range ``[0,1]`` describing a relative position of the room under the given tag.
	Order float32 `json:"order,omitempty"`
}
