/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20046 struct {
	// Experimental features the server supports. Features not listed here, or the lack of this property all together, indicate that a feature is not supported.
	UnstableFeatures map[string]bool `json:"unstable_features,omitempty"`
	// The supported versions.
	Versions []string `json:"versions"`
}
