/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Pusher struct {
	// A string that will allow the user to identify what application owns this pusher.
	AppDisplayName string `json:"app_display_name"`
	// This is a reverse-DNS style identifier for the application. Max length, 64 chars.
	AppId string `json:"app_id"`
	Data PusherData `json:"data"`
	// A string that will allow the user to identify what device owns this pusher.
	DeviceDisplayName string `json:"device_display_name"`
	// The kind of pusher. ``\"http\"`` is a pusher that sends HTTP pokes.
	Kind string `json:"kind"`
	// The preferred language for receiving notifications (e.g. 'en' or 'en-US')
	Lang string `json:"lang"`
	// This string determines which set of device specific rules this pusher executes.
	ProfileTag string `json:"profile_tag,omitempty"`
	// This is a unique identifier for this pusher. See ``/set`` for more detail. Max length, 512 bytes.
	Pushkey string `json:"pushkey"`
}
