/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// A list of messages with a new token to request more.
type InlineResponse20036 struct {
	// A list of room events. The order depends on the ``dir`` parameter. For ``dir=b`` events will be in reverse-chronological order, for ``dir=f`` in chronological order, so that events start at the ``from`` point.
	Chunk []RoomEvent `json:"chunk,omitempty"`
	// The token the pagination ends at. If ``dir=b`` this token should be used again to request even earlier events.
	End string `json:"end,omitempty"`
	// The token the pagination starts from. If ``dir=b`` this will be the token supplied in ``from``.
	Start string `json:"start,omitempty"`
	// A list of state events relevant to showing the ``chunk``. For example, if ``lazy_load_members`` is enabled in the filter then this may contain the membership events for the senders of events in the ``chunk``.  Unless ``include_redundant_members`` is ``true``, the server may remove membership events which would have already been sent to the client in prior calls to this endpoint, assuming the membership of those members has not changed.
	State []map[string]interface{} `json:"state,omitempty"`
}
