/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Context for result, if requested.
type EventContext struct {
	// Pagination token for the end of the chunk
	End string `json:"end,omitempty"`
	// Events just after the result.
	EventsAfter []RoomEvent `json:"events_after,omitempty"`
	// Events just before the result.
	EventsBefore []RoomEvent `json:"events_before,omitempty"`
	// The historic profile information of the users that sent the events returned.  The ``string`` key is the user ID for which the profile belongs to.
	ProfileInfo map[string]UserProfile `json:"profile_info,omitempty"`
	// Pagination token for the start of the chunk
	Start string `json:"start,omitempty"`
}
