/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject12 struct {
	// The keys to be downloaded. A map from user ID, to a list of device IDs, or to an empty list to indicate all devices for the corresponding user.
	DeviceKeys map[string][]string `json:"device_keys"`
	// The time (in milliseconds) to wait when downloading keys from remote servers. 10 seconds is the recommended default.
	Timeout int32 `json:"timeout,omitempty"`
	// If the client is fetching keys as a result of a device update received in a sync request, this should be the 'since' token of that sync request, or any later sync token. This allows the server to ensure its response contains the keys advertised by the notification in that sync.
	Token string `json:"token,omitempty"`
}
