/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20024 struct {
	// The user's avatar URL if they have set one, otherwise not present.
	AvatarUrl string `json:"avatar_url,omitempty"`
}
