/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject14 struct {
	// Third party identifier for the user.  Deprecated in favour of ``identifier``.
	Address string `json:"address,omitempty"`
	// ID of the client device. If this does not correspond to a known client device, a new device will be created. The server will auto-generate a device_id if this is not specified.
	DeviceId string `json:"device_id,omitempty"`
	Identifier UserIdentifier `json:"identifier,omitempty"`
	// A display name to assign to the newly-created device. Ignored if ``device_id`` corresponds to a known device.
	InitialDeviceDisplayName string `json:"initial_device_display_name,omitempty"`
	// When logging in using a third party identifier, the medium of the identifier. Must be 'email'.  Deprecated in favour of ``identifier``.
	Medium string `json:"medium,omitempty"`
	// Required when ``type`` is ``m.login.password``. The user's password.
	Password string `json:"password,omitempty"`
	// Required when ``type`` is ``m.login.token``. Part of `Token-based`_ login.
	Token string `json:"token,omitempty"`
	// The login type being used.
	Type string `json:"type"`
	// The fully qualified user ID or just local part of the user ID, to log in.  Deprecated in favour of ``identifier``.
	User string `json:"user,omitempty"`
}
