/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20020 struct {
	// An access token for the account. This access token can then be used to authorize other requests.
	AccessToken string `json:"access_token,omitempty"`
	// ID of the logged-in device. Will be the same as the corresponding parameter in the request, if one was specified.
	DeviceId string `json:"device_id,omitempty"`
	// The server_name of the homeserver on which the account has been registered.  **Deprecated**. Clients should extract the server_name from ``user_id`` (by splitting at the first colon) if they require it. Note also that ``homeserver`` is not spelt this way.
	HomeServer string `json:"home_server,omitempty"`
	// The fully-qualified Matrix ID that has been registered.
	UserId string `json:"user_id,omitempty"`
	// Optional client configuration provided by the server. If present, clients SHOULD use the provided object to reconfigure themselves, optionally validating the URLs within. This object takes the same form as the one returned from .well-known autodiscovery.
	WellKnown map[string]map[string]interface{} `json:"well_known,omitempty"`
}
