/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20031 struct {
	// An access token for the account. This access token can then be used to authorize other requests. Required if the ``inhibit_login`` option is false.
	AccessToken string `json:"access_token,omitempty"`
	// ID of the registered device. Will be the same as the corresponding parameter in the request, if one was specified. Required if the ``inhibit_login`` option is false.
	DeviceId string `json:"device_id,omitempty"`
	// The server_name of the homeserver on which the account has been registered.  **Deprecated**. Clients should extract the server_name from ``user_id`` (by splitting at the first colon) if they require it. Note also that ``homeserver`` is not spelt this way.
	HomeServer string `json:"home_server,omitempty"`
	// The fully-qualified Matrix user ID (MXID) that has been registered.  Any user ID returned by this API must conform to the grammar given in the `Matrix specification <../appendices.html#user-identifiers>`_.
	UserId string `json:"user_id"`
}
