/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RoomMember struct {
	// The mxc avatar url of the user this object is representing.
	AvatarUrl string `json:"avatar_url,omitempty"`
	// The display name of the user this object is representing.
	DisplayName string `json:"display_name,omitempty"`
}
