/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Counts of unread notifications for this room. See the `Receiving notifications section <#receiving-notifications>`_ for more information on how these are calculated.
type UnreadNotificationCounts struct {
	// The number of unread notifications for this room with the highlight flag set
	HighlightCount int32 `json:"highlight_count,omitempty"`
	// The total number of unread notifications for this room
	NotificationCount int32 `json:"notification_count,omitempty"`
}
