/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject16 struct {
	// The new avatar URL for this user.
	AvatarUrl string `json:"avatar_url,omitempty"`
}
