/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Requests that the server partitions the result set based on the provided list of keys.
type Groupings struct {
	// List of groups to request.
	GroupBy []Group `json:"group_by,omitempty"`
}
