/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject18 struct {
	Filter Filter `json:"filter,omitempty"`
	// Whether or not to include all known networks/protocols from application services on the homeserver. Defaults to false.
	IncludeAllNetworks bool `json:"include_all_networks,omitempty"`
	// Limit the number of results returned.
	Limit int32 `json:"limit,omitempty"`
	// A pagination token from a previous request, allowing clients to get the next (or previous) batch of rooms.  The direction of pagination is specified solely by which token is supplied, rather than via an explicit flag.
	Since string `json:"since,omitempty"`
	// The specific third party network/protocol to request from the homeserver. Can only be used if ``include_all_networks`` is false.
	ThirdPartyInstanceId string `json:"third_party_instance_id,omitempty"`
}
