/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Used by servers to indicate that additional authentication information is required,
type AuthenticationResponse struct {
	// A list of the stages the client has completed successfully
	Completed []string `json:"completed,omitempty"`
	// A list of the login flows supported by the server for this API.
	Flows []AuthenticationResponseFlows `json:"flows"`
	// Contains any information that the client will need to know in order to use a given type of authentication. For each login type presented, that type may be present as a key in this dictionary. For example, the public part of an OAuth client ID could be given here.
	Params map[string]map[string]interface{} `json:"params,omitempty"`
	// This is a session identifier that the client must pass back to the home server, if one is provided, in subsequent attempts to authenticate in the same API call.
	Session string `json:"session,omitempty"`
}
