/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject6 struct {
	// The new display name for this device. If not given, the display name is unchanged.
	DisplayName string `json:"display_name,omitempty"`
}
