/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject20 struct {
	// The action(s) to perform when the conditions for this rule are met.
	Actions []string `json:"actions"`
	// The conditions that must hold true for an event in order for a rule to be applied to an event. A rule with no conditions always matches. Only applicable to ``underride`` and ``override`` rules.
	Conditions []map[string]interface{} `json:"conditions,omitempty"`
	// Only applicable to ``content`` rules. The glob-style pattern to match against.
	Pattern string `json:"pattern,omitempty"`
}
