/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type User struct {
	// The avatar url, as an MXC, if one exists.
	AvatarUrl string `json:"avatar_url,omitempty"`
	// The display name of the user, if one exists.
	DisplayName string `json:"display_name,omitempty"`
	// The user's matrix user ID.
	UserId string `json:"user_id"`
}
