/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20042 struct {
	// An access token the consumer may use to verify the identity of the person who generated the token. This is given to the federation API ``GET /openid/userinfo``.
	AccessToken string `json:"access_token"`
	// The number of seconds before this token expires and a new one must be generated.
	ExpiresIn int32 `json:"expires_in"`
	// The homeserver domain the consumer should use when attempting to verify the user's identity.
	MatrixServerName string `json:"matrix_server_name"`
	// The string ``Bearer``.
	TokenType string `json:"token_type"`
}
