/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Identification information for the user.
type UserIdentifier struct {
	// The type of identification.  See `Identifier types`_ for supported values and additional property descriptions.
	Type string `json:"type"`
}
