/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ConnectionInfo struct {
	// Most recently seen IP address of the session.
	Ip string `json:"ip,omitempty"`
	// Unix timestamp that the session was last active.
	LastSeen int64 `json:"last_seen,omitempty"`
	// User agent string last seen in the session.
	UserAgent string `json:"user_agent,omitempty"`
}
