/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20041 struct {
	// The user account data that isn't associated with rooms to include.
	AccountData map[string]interface{} `json:"account_data,omitempty"`
	// List of event fields to include. If this list is absent then all fields are included. The entries may include '.' characters to indicate sub-fields. So ['content.body'] will include the 'body' field of the 'content' object. A literal '.' character in a field name may be escaped using a '\\\\'. A server may include more fields than were requested.
	EventFields []string `json:"event_fields,omitempty"`
	// The format to use for events. 'client' will return the events in a format suitable for clients. 'federation' will return the raw event as received over federation. The default is 'client'.
	EventFormat string `json:"event_format,omitempty"`
	// The presence updates to include.
	Presence map[string]interface{} `json:"presence,omitempty"`
	Room RoomFilter `json:"room,omitempty"`
}
