/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SessionInfo struct {
	// Information particular connections in the session.
	Connections []ConnectionInfo `json:"connections,omitempty"`
}
