/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Updates to rooms.
type Rooms struct {
	// The rooms that the user has been invited to.
	Invite map[string]InvitedRoom `json:"invite,omitempty"`
	// The rooms that the user has joined.
	Join map[string]JoinedRoom `json:"join,omitempty"`
	// The rooms that the user has left or been banned from.
	Leave map[string]LeftRoom `json:"leave,omitempty"`
}
