/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20025 struct {
	// The user's display name if they have set one, otherwise not present.
	Displayname string `json:"displayname,omitempty"`
}
