/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeviceInfo struct {
	// A user's sessions (i.e. what they did with an access token from one login).
	Sessions []SessionInfo `json:"sessions,omitempty"`
}
