/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The push rule.
type InlineResponse20030 struct {
	// The actions to perform when this rule is matched.
	Actions []string `json:"actions"`
	// The conditions that must hold true for an event in order for a rule to be applied to an event. A rule with no conditions always matches. Only applicable to ``underride`` and ``override`` rules.
	Conditions []map[string]interface{} `json:"conditions,omitempty"`
	// Whether this is a default rule, or has been set explicitly.
	Default bool `json:"default"`
	// Whether the push rule is enabled or not.
	Enabled bool `json:"enabled"`
	// The glob-style pattern to match against.  Only applicable to ``content`` rules.
	Pattern string `json:"pattern,omitempty"`
	// The ID of this rule.
	RuleId string `json:"rule_id"`
}
