/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserProfile struct {
	AvatarUrl string `json:"avatar_url,omitempty"`
	Displayname string `json:"displayname,omitempty"`
}
