/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Information about the newly created room.
type InlineResponse2006 struct {
	// The created room's ID.
	RoomId string `json:"room_id"`
}
