/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject15 struct {
	// The new presence state.
	Presence string `json:"presence"`
	// The status message to attach to this state.
	StatusMsg string `json:"status_msg,omitempty"`
}
