/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject5 struct {
	// Additional authentication information for the user-interactive authentication API.
	Auth map[string]map[string]interface{} `json:"auth,omitempty"`
	// The list of device IDs to delete.
	Devices []string `json:"devices"`
}
