/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Room Events have the following fields.
type RoomEvent struct {
	// The ID of the room associated with this event. Will not be present on events that arrive through ``/sync``, despite being required everywhere else.
	RoomId string `json:"room_id"`
}
