/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20044 struct {
	// Indicates if the result list has been truncated by the limit.
	Limited bool `json:"limited"`
	// Ordered by rank and then whether or not profile info is available.
	Results []User `json:"results"`
}
