/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject8 struct {
	// Whether the room should be visible (public) in the directory or not (private).
	Visibility string `json:"visibility"`
}
