/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20032 struct {
	// A flag to indicate that the username is available. This should always be ``true`` when the server replies with 200 OK.
	Available bool `json:"available,omitempty"`
}
