/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// A dictionary of information for the pusher implementation itself.
type PusherData struct {
	// The format to use when sending notifications to the Push Gateway.
	Format string `json:"format,omitempty"`
	// Required if ``kind`` is ``http``. The URL to use to send notifications to.
	Url string `json:"url,omitempty"`
}
