/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Configures whether any context for the events returned are included in the response.
type IncludeEventContext struct {
	// How many events after the result are returned. By default, this is ``5``.
	AfterLimit int32 `json:"after_limit,omitempty"`
	// How many events before the result are returned. By default, this is ``5``.
	BeforeLimit int32 `json:"before_limit,omitempty"`
	// Requests that the server returns the historic profile information for the users that sent the events that were returned. By default, this is ``false``.
	IncludeProfile bool `json:"include_profile,omitempty"`
}
