/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Describes which categories to search in and their criteria.
type Categories struct {
	RoomEvents RoomEventsCriteria `json:"room_events,omitempty"`
}
