/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20034 struct {
	// A map from user ID to a RoomMember object.
	Joined map[string]RoomMember `json:"joined,omitempty"`
}
