/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The third party credentials to associate with the account.
type ThreePidCredentials struct {
	// The client secret used in the session with the identity server.
	ClientSecret string `json:"client_secret"`
	// The identity server to use.
	IdServer string `json:"id_server"`
	// The session identifier given by the identity server.
	Sid string `json:"sid"`
}
