/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject32 struct {
	// The length of time in milliseconds to mark this user as typing.
	Timeout int32 `json:"timeout,omitempty"`
	// Whether the user is typing or not. If ``false``, the ``timeout`` key can be omitted.
	Typing bool `json:"typing"`
}
