/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// A Matrix-level Error
type InlineResponse403 struct {
	// An error code.
	Errcode string `json:"errcode"`
	// A human-readable error message.
	Error string `json:"error,omitempty"`
}
