/*
 * Matrix Client-Server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: unstable
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20021 struct {
	// The token to supply in the ``from`` param of the next ``/notifications`` request in order to request more events. If this is absent, there are no more results.
	NextToken string `json:"next_token,omitempty"`
	// The list of events that triggered notifications.
	Notifications []Notification `json:"notifications"`
}
